import { html, render } from '@mantou/gem';

import '@gem-bind/diff2html';
import '../elements/layout';

const strInput =
  '--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {\n+\tr0, _, e1 := Syscall6(SYS_PSELECT6, uintptr(nfd), uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)), uintptr(unsafe.Pointer(sigmask)))\n+\tn = int(r0)\n+\tif e1 != 0 {\n+\t\terr = errnoErr(e1)\n+\t}\n+\treturn\n+}\n+\n+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n+\n func read(fd int, p []byte) (n int, err error) {\n \tvar _p0 unsafe.Pointer\n \tif len(p) > 0 {\n';

const modified = `diff --git a/src/greet.ts b/src/greet.ts
index 1c2d3e4..5f6a7b8 100644
--- a/src/greet.ts
+++ b/src/greet.ts
@@ -1,6 +1,7 @@
-export function greet(name: string) {
-  return 'Hello, ' + name;
+export function greet(name: string, punctuation = '!') {
+  return \`Hello, \${name}\${punctuation}\`;
 }
 export function farewell(name: string) {
-  return 'Bye, ' + name;
+  const trimmed = name.trim();
+  return \`Bye, \${trimmed}\`;
 }
`;

const multiFile = `${modified}diff --git a/src/style.css b/src/style.css
index 2b3c4d5..6e7f8a9 100644
--- a/src/style.css
+++ b/src/style.css
@@ -1,4 +1,4 @@
 .greeting {
-  color: red;
+  color: rebeccapurple;
   font-weight: bold;
 }
diff --git a/src/legacy.js b/src/legacy.js
deleted file mode 100644
index 3c4d5e6..0000000
--- a/src/legacy.js
+++ /dev/null
@@ -1,3 +0,0 @@
-module.exports = function greet(name) {
-  return 'Hello, ' + name;
-};
diff --git a/README.md b/README.md
new file mode 100644
index 0000000..7a8b9c0
--- /dev/null
+++ b/README.md
@@ -0,0 +1,3 @@
+# Greeter
+
+Say hello and goodbye.
`;

render(
  html`
    <gem-examples-layout>
      <main>
        <style>
          main {
            display: flex;
            flex-direction: column;
            gap: 2em;
          }
          section {
            display: flex;
            flex-direction: column;
            gap: 0.5em;
          }
          h2 {
            margin: 0;
            font-size: 1em;
          }
          p {
            margin: 0;
            color: #666;
            font-size: 0.875em;
          }
        </style>

        <section>
          <h2>Line by line</h2>
          <p>Default output, syntax highlighted by the file extension.</p>
          <gem-bind-diff2html>${modified}</gem-bind-diff2html>
        </section>

        <section>
          <h2>Side by side, dark</h2>
          <p><code>output-format="side-by-side" color-scheme="dark" matching="lines"</code></p>
          <gem-bind-diff2html output-format="side-by-side" color-scheme="dark" matching="lines">${modified}</gem-bind-diff2html>
        </section>

        <section>
          <h2>Multiple files with file list</h2>
          <p><code>draw-file-list</code>: modified, deleted and added files in one diff.</p>
          <gem-bind-diff2html draw-file-list>${multiFile}</gem-bind-diff2html>
        </section>

        <section>
          <h2>Compact, without header</h2>
          <p><code>compact-line-numbers no-header</code>: long lines scroll under fixed line numbers.</p>
          <gem-bind-diff2html compact-line-numbers no-header>${strInput}</gem-bind-diff2html>
        </section>

        <section>
          <h2>Fill a fixed height</h2>
          <p>The last file stretches to the element's height, so the blank area still scrolls horizontally.</p>
          <gem-bind-diff2html style="height: 400px" color-scheme="dark" compact-line-numbers no-header>${strInput}</gem-bind-diff2html>
        </section>

        <section>
          <h2>Character diff, no highlighting</h2>
          <p><code>diff-style="char" no-highlight</code></p>
          <gem-bind-diff2html diff-style="char" no-highlight>${modified}</gem-bind-diff2html>
        </section>
      </main>
    </gem-examples-layout>
  `,
  document.body,
);
